### ISSUE TITLE
Support for FSB5 without names

### ISSUE THREAD

**Issue by bnnm** [CyberBotX/fsb5_split#1]
Rarely FSB5 don't have a name table (size at 0x10 is 0). fsb5_split will extract every file as ".fsb", and also overwrite them, so in the end only the last file gets extracted.
Probably should generate a name like filename_xxx.fsb if the table doesn't exist, or as an option.

Example from Forza Horizon 3: [00000000.zip](https://github.com/CyberBotX/fsb5_split/files/1835402/00000000.zip)
That FSB5 seems to have names in a flag, but I think some don't have any names at all.

**Comment by CyberBotX** [comment]
Sorry I never got around to this until now, but it should be fixed with the latest commit.
